http:
  port: 8085
admin:
  port: 9875
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  user:
    host: localhost 
    paths: '/hero/*'
    methods: ["POST"]

  body:
    host: localhost
    paths: '/powerBody'
    methods: ["POST"]
  product:
     host: localhost
     paths: '/product'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  user:
    url: 'http://localhost:3000'
  product:
    url: 'http://localhost:3001'
  body:
    url: 'http://localhost:3000'  
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  
  default2:
    apiEndpoints:
      - user
    policies:      
      - proxy:
        - action:
            
            serviceEndpoint: user
            changeOrigin: true

  default3:
    apiEndpoints:
       - product 
    policies:
        - proxy:
          - action:
              serviceEndpoint: product
              changeOrigin: true

  default4:
    apiEndpoints:
       - body 
    policies:
        - proxy:
          - action:
              serviceEndpoint: body
              changeOrigin: true